-- DATA CLEANING PROJECT

-- https://www.kaggle.com/datasets/swaptr/layoffs-2022
SELECT * 
FROM layoffs;
 
 -- WE CREATE A DUPLICATE (STAGING TABLE) SO ORIGINAL DATA REMAINS SAFE
CREATE TABLE LAYOFFS_STAGING
LIKE LAYOFFS;

INSERT INTO LAYOFFS_STAGING
SELECT * FROM LAYOFFS;

-- STEPS  FOR DATA CLEANING ARE AS FOLLOWS:
-- 1. REMOVE DUPLICATES
-- 2. STANDARDIZE THE DATA
-- 3. HANDLE NULL VALUES OR BLANK VALUES
-- 4. REMOVE UNNECESSARY COLUMNS

SELECT * FROM LAYOFFS_STAGING;

-- IDENTIFY DUPLICATES
WITH DUPLICATE_CTE AS
(SELECT * ,
ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY, TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,'DATE',STAGE,COUNTRY,
FUNDS_RAISED_MILLIONS) AS ROW_NUM
 FROM LAYOFFS_STAGING
 )
SELECT *
FROM DUPLICATE_CTE
WHERE ROW_NUM>1;

SELECT * FROM LAYOFFS_STAGING
WHERE COMPANY='CASPER';


CREATE TABLE `layoffs_staging2` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  ROW_NUM INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM layoffs_staging2;

INSERT INTO LAYOFFS_STAGING2
SELECT * ,
ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY, TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,'DATE',STAGE,COUNTRY,
FUNDS_RAISED_MILLIONS) AS ROW_NUM
 FROM LAYOFFS_STAGING;

-- DELETING DUPLICATES
DELETE FROM layoffs_staging2
WHERE ROW_NUM>1;

-- TURN OFF SQL SAFE UPDATE MODE
SET SQL_SAFE_UPDATES=0;

-- CHECK IF DUPLICATES DELETE OR NOT
SELECT * FROM LAYOFFS_STAGING2
WHERE ROW_NUM>1;

-- STANDARDIZE DATA
-- REMOVES UNWANTED SPACES FROM COMPANY NAMES
SELECT COMPANY,TRIM(COMPANY) FROM LAYOFFS_STAGING2;
 
UPDATE LAYOFFS_STAGING2
SET COMPANY=TRIM(COMPANY);

SELECT * FROM LAYOFFS_STAGING2;

SELECT DISTINCT INDUSTRY FROM LAYOFFS_STAGING2
ORDER BY 1;

-- FIX INDUSTRY NAMES
UPDATE LAYOFFS_STAGING2
SET INDUSTRY="Crypto"
WHERE INDUSTRY LIKE "CRYPTO%";

SELECT DISTINCT LOCATION
FROM LAYOFFS_STAGING2
ORDER BY 1;
-- EVERYTHING IS OK IN LOCATION

SELECT DISTINCT COUNTRY FROM LAYOFFS_STAGING2
ORDER BY 1;

SELECT DISTINCT COUNTRY,TRIM(TRAILING'.'FROM COUNTRY)
FROM LAYOFFS_STAGING2;

-- FIX COUNTRY NAMES
UPDATE LAYOFFS_STAGING2
SET COUNTRY=TRIM(TRAILING'.' FROM COUNTRY)
WHERE COUNTRY LIKE "UNITED STATES%";

-- CONVERT DATE FORMAT
SELECT date,
STR_TO_DATE(date,'%m/%d/%Y')
FROM LAYOFFS_STAGING2;

UPDATE LAYOFFS_STAGING2
SET DATE=STR_TO_DATE(date,'%m/%d/%Y');

SELECT * FROM LAYOFFS_STAGING2;

-- CHANGE DATA TYPE OF DATE
ALTER TABLE LAYOFFS_STAGING2
MODIFY COLUMN date DATE;

SELECT * FROM LAYOFFS_STAGING2;

-- HANDLE NULL & BLANK VALUES
SELECT * FROM LAYOFFS_STAGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;

-- FIND MISSING DATA
SELECT * FROM LAYOFFS_STAGING2
WHERE INDUSTRY IS NULL
OR INDUSTRY ="";

SELECT * FROM LAYOFFS_STAGING2
WHERE COMPANY="AIRBNB";

-- REPLACE BLANK WITH NULL
UPDATE LAYOFFS_STAGING2
SET INDUSTRY=NULL
WHERE INDUSTRY ="";

SELECT T1.INDUSTRY,T2.INDUSTRY FROM LAYOFFS_STAGING2 AS T1
JOIN LAYOFFS_STAGING2 AS T2
ON T1.COMPANY=T2.COMPANY
WHERE T1.INDUSTRY IS NULL AND T2.INDUSTRY IS NOT NULL;

-- FILL MISSING INDUSTRY USING SAME COMPANY
UPDATE LAYOFFS_STAGING2 T1
JOIN LAYOFFS_STAGING2 T2
ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY=T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL
AND T2.INDUSTRY IS NOT NULL;

SELECT * FROM LAYOFFS_STAGING2
WHERE COMPANY LIKE "BALLY%";

SELECT * FROM LAYOFFS_STAGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;

-- DELETE UNNECESSARY DATA WHICH WE CAN'T REALLY USE
DELETE FROM LAYOFFS_STAGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;

-- REMOVE TEMPORARY COLUMN USED FOR DUPLICATE HANDLING
ALTER TABLE LAYOFFS_STAGING2
DROP COLUMN ROW_NUM;

-- FINAL CLEAN DATA
SELECT * FROM LAYOFFS_STAGING2;

