-- EXPLORATORY DATA ANALYSIS
-- Here we are jsut going to explore the data and find trends or patterns or anything interesting like outliers

SELECT * FROM LAYOFFS_STAGING2;

-- In this step, we identify the highest layoffs and percentage laid off.
SELECT MAX(TOTAL_LAID_OFF),MAX(PERCENTAGE_LAID_OFF)
FROM LAYOFFS_STAGING2;

-- In this step, we find companies where all employees were laid off.
SELECT * FROM LAYOFFS_STAGING2
WHERE PERCENTAGE_LAID_OFF=1
ORDER BY TOTAL_LAID_OFF DESC;

-- In this step, we analyze which companies had the highest layoffs.
SELECT COMPANY,SUM(TOTAL_LAID_OFF) FROM LAYOFFS_STAGING2
GROUP BY COMPANY 
ORDER BY 2 DESC;

SELECT MIN(DATE),MAX(DATE)
FROM LAYOFFS_STAGING2;

-- In this step, we find which industries were most affected.
SELECT INDUSTRY,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY INDUSTRY 
ORDER BY 2 DESC;

-- In this step, we analyze layoffs across different countries.
SELECT COUNTRY,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY COUNTRY
ORDER BY 2 DESC;

-- In this step, we analyze daily layoffs trends.
SELECT DATE,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY DATE 
ORDER BY 1 DESC;

-- In this step, we find the total layoffs by each industry and identify which industries were most affected.
SELECT INDUSTRY,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY INDUSTRY 
ORDER BY 2 DESC;

-- In this step, we analyze yearly trends of layoffs.
SELECT YEAR(DATE),SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY YEAR(DATE) 
ORDER BY 1 DESC;

-- In this step, we compare company layoffs year-wise.
SELECT YEAR(DATE),COMPANY,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY YEAR(DATE),COMPANY 
ORDER BY 1 DESC;

-- In this step, we analyze layoffs based on company stage (startup, etc.).
SELECT STAGE,SUM(TOTAL_LAID_OFF)  
FROM LAYOFFS_STAGING2
GROUP BY STAGE 
ORDER BY 2 DESC;

-- In this step, we analyze impact using percentage layoffs.
SELECT COMPANY,SUM(PERCENTAGE_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY COMPANY 
ORDER BY 2 DESC;

SELECT * FROM LAYOFFS_STAGING2;

-- In this step, we analyze layoffs month-wise.
SELECT SUBSTRING(DATE,1,7) AS MONTH,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(DATE,1,7) IS NOT NULL
GROUP BY MONTH
ORDER BY 1 ASC;

-- In this step, we calculate cumulative layoffs over time.
WITH ROLLING_TOTAL AS(
SELECT SUBSTRING(DATE,1,7) AS MONTH ,SUM(TOTAL_LAID_OFF) AS TOTAL_OFF
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(DATE,1,7) IS NOT NULL
GROUP BY MONTH
ORDER BY 1 ASC
)
SELECT MONTH,TOTAL_OFF,SUM(TOTAL_OFF) OVER(ORDER BY MONTH) AS ROLLING_TOTAL
FROM ROLLING_TOTAL;

-- In this step, we rank companies based on layoffs each year.
WITH COMPANY_YEAR (COMPANY,YEARS, TOTAL_LAID_OFF)AS
(
SELECT COMPANY,YEAR(DATE) ,SUM(TOTAL_LAID_OFF) 
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(DATE,1,7) IS NOT NULL
GROUP BY COMPANY,YEAR(DATE)
)
SELECT*,
DENSE_RANK() OVER(PARTITION BY YEARS ORDER BY TOTAL_LAID_OFF DESC) AS RANKING
FROM COMPANY_YEAR
ORDER BY RANKING;


-- In this step, we find top 5 companies with highest layoffs per year.
WITH COMPANY_YEAR (COMPANY,YEARS, TOTAL_LAID_OFF)AS
(
SELECT COMPANY,YEAR(DATE) ,SUM(TOTAL_LAID_OFF) 
FROM LAYOFFS_STAGING2
WHERE SUBSTRING(DATE,1,7) IS NOT NULL
GROUP BY COMPANY,YEAR(DATE)
),COMPANY_RANKING AS
(SELECT*,
DENSE_RANK() OVER(PARTITION BY YEARS ORDER BY TOTAL_LAID_OFF DESC) AS RANKING
FROM COMPANY_YEAR
)
SELECT * FROM COMPANY_RANKING
WHERE RANKING<=5;
